#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BOOK_DIR="$ROOT_DIR/book"
GENERATED_DIR="$ROOT_DIR/generated"
OUTPUT_DIR="$ROOT_DIR/PDF"
BOOK_FILE="$GENERATED_DIR/book.typ"
TEMPLATE_FILE="$ROOT_DIR/template.typ"
PDF_FILE="$OUTPUT_DIR/modern-dotnet-guide.pdf"

command -v pandoc >/dev/null 2>&1 || { echo "Error: pandoc is not installed or not in PATH." >&2; exit 1; }
command -v typst >/dev/null 2>&1 || { echo "Error: typst is not installed or not in PATH." >&2; exit 1; }
[[ -d "$BOOK_DIR" ]] || { echo "Error: missing book directory: $BOOK_DIR" >&2; exit 1; }
[[ -f "$TEMPLATE_FILE" ]] || { echo "Error: missing template: $TEMPLATE_FILE" >&2; exit 1; }

mkdir -p "$GENERATED_DIR" "$OUTPUT_DIR"
rm -f "$GENERATED_DIR"/*.typ

# Bash expands this glob in filename order. Use zero-padded names such as
# 01-introduction.md, 02-modern-dotnet.md, and 10-docker.md.
chapters=("$BOOK_DIR"/[0-9][0-9]-*.md)

if [[ ! -e "${chapters[0]}" ]]; then
  echo "Error: no Markdown chapters found in $BOOK_DIR" >&2
  exit 1
fi

printf '// Generated by build.sh. Do not edit.\n\n' > "$BOOK_FILE"

echo "Converting chapters:"
for chapter in "${chapters[@]}"; do
  filename="$(basename "$chapter")"
  stem="${filename%.md}"
  generated_file="$GENERATED_DIR/$stem.typ"

  echo "  $filename"
  pandoc "$chapter" \
    --from=markdown \
    --to=typst \
    --output="$generated_file"

  printf '#include "%s.typ"\n#pagebreak(weak: true)\n\n' "$stem" >> "$BOOK_FILE"
done

echo "Compiling PDF..."
typst compile --root "$ROOT_DIR" "$TEMPLATE_FILE" "$PDF_FILE"

echo
echo "Book created:"
echo "  $PDF_FILE"
